

const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: '⭐⭐⭐⭐⭐',
    prevPrice: "₹3500",
    newPrice: "2000",
    company: "Nike",
    rating: "5",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: '⭐⭐⭐⭐',
    prevPrice: "₹3200",
    newPrice: "1500",
    company: "Nike",
    rating: "4",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    star: '⭐⭐⭐',
    prevPrice: "₹4000",
    newPrice: "1000",
    company: "Nike",
    rating: "3",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    star: '⭐⭐⭐⭐',
    prevPrice: "₹4500",
    newPrice: "2000",
    company: "Adidas",
    rating: "4",
    category: "sneakers",
  },
  {
    img: "https://rb.gy/9r81a",
    title: "Flat Slip On Pumps",
    star: '⭐⭐⭐⭐',
    prevPrice: "₹2500",
    newPrice: "1500",
    company: "Vans",
    rating: "4",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: '⭐',
    prevPrice: "₹1400",
    newPrice: "500",
    company: "Adidas",
    rating: "1",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: '⭐⭐⭐⭐',
    prevPrice: "₹1400",
    newPrice: "500",
    company: "Vans",
    rating: "4",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: '⭐⭐⭐⭐⭐',
    prevPrice: "₹4000",
    newPrice: "1500",
    company: "Nike",
    rating: "5",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: '⭐⭐⭐⭐⭐',
    prevPrice: "₹5000",
    newPrice: "2000",
    company: "Adidas",
    rating: "5",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: '⭐⭐⭐⭐',
    prevPrice: "₹4000",
    newPrice: "1500",
    company: "Puma",
    rating: "4",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: '⭐⭐',
    prevPrice: "₹2500",
    newPrice: "1000",
    company: "Puma",
    rating: "2",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: '⭐⭐⭐',
    prevPrice: "₹1500",
    newPrice: "500",
    company: "Puma",
    rating: "3",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: '⭐⭐⭐',
    prevPrice: "₹4000",
    newPrice: "1500",
    company: "Puma",
    rating: "3",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: '⭐',
    prevPrice: "₹1400",
    newPrice: "500",
    company: "Puma",
    rating: "1",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: '⭐',
    prevPrice: "₹1400",
    newPrice: "1000",
    company: "Puma",
    rating: "1",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: '⭐⭐',
    prevPrice: "₹3500",
    newPrice: "1000",
    company: "Vans",
    rating: "2",
    category: "flats",
  },
  {
    img: "https://t.ly/Rh2Uu",
    title: "Low-Top Trainers",
    star: '⭐⭐',
    prevPrice: "₹4000",
    newPrice: "1500",
    company: "Vans",
    rating: "2",
    category: "sandals",
  },
  {
    img: "https://t.ly/Rh2Uu",
    title: "Vans Unisex Low-Top",
    star: '⭐',
    prevPrice: "₹1400",
    newPrice: "1000",
    company: "Vans",
    rating: "1",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "classNameic Bandana Sneakers",
    star: '⭐⭐⭐',
    prevPrice: "₹2000",
    newPrice: "1500",
    company: "Nike",
    rating: "3",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: '⭐⭐⭐⭐',
    prevPrice: "₹1500",
    newPrice: "500",
    company: "Vans",
    rating: "4",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: '⭐⭐⭐⭐⭐',
    prevPrice: "₹2000",
    newPrice: "1500",
    company: "puma",
    rating: "5",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: '⭐⭐⭐⭐⭐',
    prevPrice: "₹2000",
    newPrice: "1000",
    company: "Nike",
    rating: "5",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: '⭐⭐⭐⭐',
    prevPrice: "₹2400",
    newPrice: "1000",
    company: "Nike",
    rating: "4",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: '⭐⭐⭐',
    prevPrice: "₹4000",
    newPrice: "2000",
    company: "Nike",
    rating: "3",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    star: '⭐⭐',
    prevPrice: "₹1200",
    newPrice: "500",
    company: "Adidas",
    rating: "2",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    star: '⭐',
    prevPrice: "₹1400",
    newPrice: "500",
    company: "Adidas",
    rating: "1",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    star: '⭐⭐⭐⭐⭐',
    prevPrice: "₹1500",
    newPrice: "1000",
    company: "Adidas",
    rating: "5",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    star: '⭐',
    prevPrice: "₹1400",
    newPrice: "500",
    company: "Adidas",
    rating: "1",
    category: "flats",
  },
];

export default data;